### ISSUE TITLE
cv2 import issue in jupyter notebook, but works in python cli inside conda environment

### ISSUE THREAD

**Issue by ptgamr** [udacity/P1_Facial_Keypoints#13]
When I ran first cell on Notebook 1, I got the following error:
```
ModuleNotFoundError: No module named 'cv2'
```
But when I enter python cli within the anaconda env, `import cv2` works just fine. 

Any idea?

**Comment by ptgamr** [comment]
This is my pip install btw,

```
(cv-nd) ➜  P1_Facial_Keypoints git:(master) ✗ pip install -r requirements.txt
Requirement already satisfied: opencv-python==3.2.0.6 in /home/ptgamr/anaconda3/envs/cv-nd/lib/python3.6/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: matplotlib==2.1.1 in /home/ptgamr/anaconda3/envs/cv-nd/lib/python3.6/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: pandas==0.22.0 in /home/ptgamr/anaconda3/envs/cv-nd/lib/python3.6/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: numpy==1.12.1 in /home/ptgamr/anaconda3/envs/cv-nd/lib/python3.6/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: pillow==5.0.0 in /home/ptgamr/anaconda3/envs/cv-nd/lib/python3.6/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: scipy==1.0.0 in /home/ptgamr/anaconda3/envs/cv-nd/lib/python3.6/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: six>=1.10 in /home/ptgamr/anaconda3/envs/cv-nd/lib/python3.6/site-packages (from matplotlib==2.1.1->-r requirements.txt (line 2))
Requirement already satisfied: python-dateutil>=2.0 in /home/ptgamr/anaconda3/envs/cv-nd/lib/python3.6/site-packages (from matplotlib==2.1.1->-r requirements.txt (line 2))
Requirement already satisfied: cycler>=0.10 in /home/ptgamr/anaconda3/envs/cv-nd/lib/python3.6/site-packages (from matplotlib==2.1.1->-r requirements.txt (line 2))
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/ptgamr/anaconda3/envs/cv-nd/lib/python3.6/site-packages (from matplotlib==2.1.1->-r requirements.txt (line 2))
Requirement already satisfied: pytz in /home/ptgamr/anaconda3/envs/cv-nd/lib/python3.6/site-packages (from matplotlib==2.1.1->-r requirements.txt (line 2))
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(cv-nd) ➜  P1_Facial_Keypoints git:(master) ✗ 
```

**Comment by sunsided** [comment]
It could be that it's not picking up your environment. If that is true, try installing `nb_conda` within your environment and then start Jupyter from there.

```bash
conda install nb_conda
```

This should allow you to select the correct kernel in the notebook (e.g. via the Kernel menu).

**Comment by cezannec** [comment]
Yes, I suspect it's the environment. Another solution, that shouldn't require an install, is that you can also go to the top of your notebook and click Kernel > Change Kernel > cv-nd . I bet you are not the only one experiencing this problem and so I will add some clarifications to the readme instructions :) thank you!

**Comment by ptgamr** [comment]
![2018-05-01_09 52 54](https://user-images.githubusercontent.com/1619740/39452186-75b8af66-4d25-11e8-8aad-107b6fdd54c8.png)

@cezannec I don't see `cv-nd` option when changing the kernel. Am I missing something?

**Comment by cezannec** [comment]
Hmm, I see, did you follow the instructions for environment creation in the readme of this project? They guide you in creating and starting an environment named `cv-nd`. If you still don't see that option after following the instructions. I suggest that you follow sunsided's comment and in your environment install `nb_conda` which will allow you to see a dropdown list of all your environments.

**Comment by ptgamr** [comment]
@cezannec thanks. I think I figured it out... I did `conda install jupyter`  after `source activate cv-nd`, now it's picking up the correct env.

**Comment by Redwa** [comment]
Thanks @ptgamr for asking and @sunsided for answering .  It is working after I followed your instructions (conda install nb_conda)

**Comment by akshayjaryal603** [comment]
Thanks @sunsided  (conda install nb_conda) this command help me a lot. I puzzled for two days for resolving this error then I found this error. @cezannec ma'am please include this command in the readme file.

**Comment by radu941208** [comment]
This helped me so much; i spent hours figuring out system variables and path and finally, i got the right Issue Page.
Thanks

**Comment by zabir-nabil** [comment]
Add virtual environment to jupyter notebook.
After activating conda virtual environment ( `conda activate virtual_env` ), install ipykernel ( `pip install ipykernel` ), finally add the virtual_env to jupyter notebook with ( `python -m ipykernel install --user --name=virtual_env` ). Now, inside jupyter notebook select the virtual_env instead of default python installation.

**Comment by shivani792** [comment]
i follow the step of @sunsided and @cezannec but still faced same problem.module cv2 is not found.plz help me to figure out this.`ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-d0462338b391> in <module>
      1 import os
----> 2 import cv2
      3 import numpy as np
      4 from matplotlib import pyplot as plt
      5 get_ipython().run_line_magic('matplotlib', 'inline')

ModuleNotFoundError: No module named 'cv2'
`

**Comment by gowrusreevathsa** [comment]
This helped me.
I created a new `cv-nd` environment using the command  `conda create -n yourenvname python=x.x anaconda`. The env name is `cv-nd` and I didn't specify python version so my command looked `conda create -n cv-nd anaconda`. 
Then activate the environment using `conda activate cv-nd`. 
Then install required libraries using conda commands. I installed jupyter and cv2 in this environment. You can find commands for cv2 at https://anaconda.org/conda-forge/opencv Navigate that website as per your requirement.

**Comment by gowrusreevathsa** [comment]
> i follow the step of @sunsided and @cezannec but still faced same problem.module cv2 is not found.plz help me to figure out this.`ModuleNotFoundError Traceback (most recent call last)
> in
> 1 import os
> ----> 2 import cv2
> 3 import numpy as np
> 4 from matplotlib import pyplot as plt
> 5 get_ipython().run_line_magic('matplotlib', 'inline')
> 
> ModuleNotFoundError: No module named 'cv2'
> `

Try following the method I mentioned below that worked for me.

**Comment by gowrusreevathsa** [comment]
> i follow the step of @sunsided and @cezannec but still faced same problem.module cv2 is not found.plz help me to figure out this.`ModuleNotFoundError Traceback (most recent call last)
> in
> 1 import os
> ----> 2 import cv2
> 3 import numpy as np
> 4 from matplotlib import pyplot as plt
> 5 get_ipython().run_line_magic('matplotlib', 'inline')
> 
> ModuleNotFoundError: No module named 'cv2'
> `

Try following the method I mentioned above. It might work for you.

**Comment by Kamil2412** [comment]
OpenCV is compiled for Python 2.7. When you install it with pip, it will install 2.7. However, if you run the code with python 3, it will complain that the module is not installed.
using the command
 `sudo apt-get install python3-opencv`


Solved my problem, hope it will help others

**Comment by leohfigueiredo** [comment]
`conda install nb_conda` works for me. Thanks.

**Comment by KFatma** [comment]
pip install opencv-python
This worked for me!

**Comment by sanskarfc** [comment]
> It could be that it's not picking up your environment. If that is true, try installing `nb_conda` within your environment and then start Jupyter from there.
> 
> ```shell
> conda install nb_conda
> ```
> 
> This should allow you to select the correct kernel in the notebook (e.g. via the Kernel menu).

THANK YOU SO MUCH! YOU ARE A LIFE-SAVER
