### ISSUE TITLE
 ResolvePackageNotFound: 

### ISSUE THREAD

**Issue by essalahsouad** [udacity/P1_Facial_Keypoints#21]
@sunsided Hi, I have a question about your repository facial key point detection, when I was trying to follow your steps 
`conda env create -f environment.yaml`
I got an error 

> ResolvePackageNotFound: 
- nbconvert==5.3.1=py_1
i'm using ubuntu 18
python3.6

**Comment by sunsided** [comment]
Not sure why that happens. The `nbconvert` dependency was a transient one and thus should be pulled automatically anyways. I have removed the according line from both `environment.yaml` and `environment-cuda.yaml` (commit 869fb721280dd93cf89e22a997061d38f72536a4 in [my fork](https://github.com/sunsided/facial-keypoints)).

**Comment by sunsided** [comment]
I also have enabled the Issues feature in my repo. :upside_down_face:
